In [5]:
# Import Dependencies 
import pandas as pd

In [6]:
# Save original data as a variable to be read 
original_data = "original_dataset.csv"

In [7]:
# Read our Data file with the pandas library
original_data_df = pd.read_csv(original_data)
original_data_df.head()

,statecode,countycode,fipscode,state,county,year,county_ranked,v001_rawvalue,v001_numerator,v001_denominator,...,v013_rawvalue,v016_rawvalue,v017_rawvalue,v025_rawvalue,v026_rawvalue,v027_rawvalue,v031_rawvalue,v032_rawvalue,v035_rawvalue,v097_rawvalue
0,0,0,0,US,United States,2019,NaN,6900.630354,3745538.0,908266078.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,1000,AL,Alabama,2019,NaN,9917.232898,80440.0,13636816.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1001,AL,Autauga County,2019,1.0,8824.057123,815.0,156132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,1003,AL,Baldwin County,2019,1.0,7224.632160,2827.0,576496.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,1005,AL,Barbour County,2019,1.0,9586.165037,451.0,72222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Pull columns which will be needed for future analysis

new_data = original_data_df[["state", "year", "v023_numerator", "v023_denominator", "v085_numerator", "v085_denominator", "v003_numerator", "v003_denominator", "v122_numerator", "v122_denominator", "v060_numerator", "v060_denominator", "v061_numerator", "v061_denominator", "v155_rawvalue", "v011_numerator", "v011_denominator", "v144_rawvalue", "v043_numerator", "v043_denominator", "v135_numerator", "v135_denominator", "v015_numerator", "v015_denominator", "v148_numerator", "v148_denominator", "v145_rawvalue", "v138_numerator", "v138_denominator", "v001_numerator", "v001_denominator", "v147_rawvalue", "v037_numerator", "v037_denominator", "v005_rawvalue"]]
new_data.head()

,state,year,v023_numerator,v023_denominator,v085_numerator,v085_denominator,v003_numerator,v003_denominator,v122_numerator,v122_denominator,...,v148_denominator,v145_rawvalue,v138_numerator,v138_denominator,v001_numerator,v001_denominator,v147_rawvalue,v037_numerator,v037_denominator,v005_rawvalue
0,US,2019,6994555.0,160588786.0,26749668.0,267259921.0,23533400.0,194808251.0,3559597.0,76219054.0,...,1.605251e+09,NaN,186273.0,970265511.0,3745538.0,908266078.0,79.063850,2230947.0,27579119.0,NaN
1,AL,2019,95342.0,2168448.0,427972.0,3973078.0,401044.0,2895627.0,30253.0,1135031.0,...,2.428012e+07,0.145488,2327.0,14597026.0,80440.0,13636816.0,75.413035,41895.0,412942.0,5496.0
2,AL,2019,1001.0,25909.0,4002.0,47077.0,3686.0,33628.0,351.0,14175.0,...,2.769080e+05,0.126384,16.0,166267.0,815.0,156132.0,76.330589,377.0,4448.0,6599.0
3,AL,2019,3652.0,91567.0,17733.0,165740.0,16389.0,120771.0,1530.0,47251.0,...,1.020551e+06,0.128226,102.0,624900.0,2827.0,576496.0,78.599498,1299.0,15578.0,3833.0
4,AL,2019,486.0,8236.0,2252.0,17997.0,2105.0,12725.0,161.0,5549.0,...,1.316870e+05,0.146323,NaN,NaN,451.0,72222.0,75.779457,215.0,1963.0,4736.0

In [ ]:
renamed_new = new_data.rename(columns={"state" :"State", 
                                       "year" :"Year", 
                                       "v023_numerator", 
                                       "v023_denominator", 
                                       "v085_numerator", 
                                       "v085_denominator", 
                                       "v003_numerator", 
                                       "v003_denominator", 
                                       "v122_numerator", 
                                       "v122_denominator", 
                                       "v060_numerator", 
                                       "v060_denominator", 
                                       "v061_numerator", 
                                       "v061_denominator", 
                                       "v155_rawvalue", 
                                       "v011_numerator", 
                                       "v011_denominator", 
                                       "v144_rawvalue", 
                                       "v043_numerator", 
                                       "v043_denominator", 
                                       "v135_numerator", 
                                       "v135_denominator", 
                                       "v015_numerator", 
                                       "v015_denominator", 
                                       "v148_numerator", 
                                       "v148_denominator", 
                                       "v145_rawvalue", 
                                       "v138_numerator", 
                                       "v138_denominator", 
                                       "v001_numerator", 
                                       "v001_denominator", 
                                       "v147_rawvalue", 
                                       "v037_numerator", 
                                       "v037_denominator", 
                                       "v005_rawvalue"]]
})